[[mgr.prepend_keymap]]
on   = "C"
run  = 'shell "$SHELL" --block --confirm'
desc = "Drop into shell"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on = "o"
run = "open --interactive"
desc = "Open selected files interactively"

[[mgr.prepend_keymap]]
on = "J"
run = "arrow bot"
desc = "Go to bottom"

[[mgr.prepend_keymap]]
on = "K"
run = "arrow top"
desc = "Go to top"
