[preview]
# This forces Yazi to use ueberzugpp for images
image_filter = "lanczos3"
image_quality = 75
max_width = 1500
max_height = 1500

[opener]
edit = [
  { run = "${EDITOR:-vi} %s", desc = "$EDITOR", block = true },
]
pdff = [
	{ run = 'zathura "$@"', orphan = true, desc = "Zathura", block = false },
	{ run = 'sioyek "$@"', orphan = true, desc = "Sioyek", block = false },
]

[open]
rules = [
  { mime = "application/pdf", use = [ "pdff" ] },
	# Folder
	{ url = "*/", use = [ "edit", "open", "reveal" ] },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal" ] },
	# Image
	{ mime = "image/*", use = [ "open", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = "download" },
	# Fallback
	{ url = "*", use = [ "edit" ]},
]


[plugin]
